apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: apps/templates/nginx
    repoURL: >-
      https://argo-cd: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@github.com/chaman53/argocd.git
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
