apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apacheD
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: apache
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/apache
    repoURL: >-
      https://argo-cd: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@github.com/chaman53/argocd.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
